version: '3.9'

services:
  nest_dev:
    container_name: 'nest_dev'
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - PORT=3000

      - DATABASE_HOST=db_dev
      - DATABASE_PORT=5432
      - DATABASE_NAME=dev_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      #- /usr/src/app/node_modules
    command: npx nest start --watch --preserveWatchOutput
    depends_on:
      - db_dev

  db_dev:
    container_name: 'nest_dev_db'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dev_db
    ports:
      - 5000:5432
    volumes:
      - ./pg_database:/var/lib/postgresql/data
